before_script: 
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update -qq
 - sudo apt-get install -y gcc-arm-none-eabi

script: make

# whitelist
branches:
  only:
    - edge
 
